# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: panzone's blog
#email:
description: > # this means to ignore newlines until "baseurl:"
  Computer scientist and software developer,
  enjoys solving problems and eating pizza. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://panzone.github.io" # the base hostname & protocol for your site
twitter_username: panzone91
github_username: panzone

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->